### ISSUE TITLE
Bias?

### ISSUE THREAD

**Issue by RoyalTS** [RoyalTS/stochatreat#2]
In the `pytest`s assigned treatments seem consistently biased in favor of the first treatment. That is, across all strata the first treatment consistently receives a larger share of the units than it should given the probs. This ought not to be the case. I suspect it's because of the misfits but have not investigated further.

**Comment by manmartgarc** [comment]
I realized that this was happening because the I was assigning treatments within each misfit block using the entire's block numbers. This has since been fixed.
